### ISSUE TITLE
Authentication with GitHub

### ISSUE THREAD

**Issue by craigcabrey** [craigcabrey/tiquet.me#1]
We need to integrate with GitHub for users to authenticate.
- `loopback-component-passport`, `passport`, and `passport-github` will all be involved.
- `loopback-sdk-angular` doesn't support cookie based authentication, so that needs to be worked around
  - https://github.com/strongloop/loopback-sdk-angular/issues/74
- Need to extend the `User` model in order to store the generate GitHub access token for each user

**Comment by craigcabrey** [comment]
Everything went better than expected.

**Comment by ahmed-abdulmoniem** [comment]
loopback-sdk-angular doesn't support cookie based authentication, so that needs to be worked around???

**Comment by craigcabrey** [comment]
Yes, we have a very simple workaround.

It can be found in `fix-token.js` in the client application code.
